export type IgnoreGroup = {
  id: string;
  label: string;
  hint: string;
  patterns: string[];
};

// selectable groups shown in the init multiselect
export const ignoreGroups: IgnoreGroup[] = [
  {
    id: "os",
    label: "OS junk files",
    hint: ".DS_Store, Thumbs.db",
    patterns: [".DS_Store", "Thumbs.db", "desktop.ini", "$RECYCLE.BIN/"],
  },
  {
    id: "node",
    label: "Node / JS",
    hint: "node_modules, logs",
    patterns: ["node_modules/", "npm-debug.log*", ".pnpm-store/", ".turbo/"],
  },
  {
    id: "env",
    label: "Environment files",
    hint: ".env, .env.*",
    patterns: [".env", ".env.*", "!.env.example"],
  },
  {
    id: "build",
    label: "Build output",
    hint: "dist, build, out",
    patterns: ["dist/", "build/", "out/", ".cache/"],
  },
  {
    id: "editor",
    label: "Editor / IDE",
    hint: ".vscode, .idea",
    patterns: [".vscode/", ".idea/", "*.swp", "*.swo"],
  },
  {
    id: "logs",
    label: "Logs & temp",
    hint: "*.log, tmp",
    patterns: ["*.log", "tmp/", "temp/"],
  },
  {
    id: "python",
    label: "Python",
    hint: "__pycache__, venv",
    patterns: ["__pycache__/", "*.pyc", ".venv/", "venv/"],
  },
  {
    id: "secrets",
    label: "Keys & secrets",
    hint: "*.pem, *.key",
    patterns: ["*.pem", "*.key", "*.p12", "credentials.json"],
  },
];

// the sync worktree itself must never be ignored
const alwaysIgnore = [".syncthing/"];

export const buildGitignore = (selectedGroupIds: string[], customPatterns: string[]): string => {
  const sections: string[] = ["# Generated by syncthing", ""];

  for (const group of ignoreGroups) {
    if (!selectedGroupIds.includes(group.id)) continue;
    sections.push(`# ${group.label}`);
    sections.push(...group.patterns);
    sections.push("");
  }

  const cleanedCustom = customPatterns.map((line) => line.trim()).filter(Boolean);
  if (cleanedCustom.length > 0) {
    sections.push("# Custom");
    sections.push(...cleanedCustom);
    sections.push("");
  }

  sections.push("# syncthing internal");
  sections.push(...alwaysIgnore);
  sections.push("");

  return sections.join("\n");
};
